apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
spec:
  selector:
    app: mon-app  # Must match the label in the deployment YAML
  ports:
    - protocol: TCP
      port: 5000  # Exposing the port on the service
      targetPort: 5000  # The container port to target
  type: LoadBalancer  # Use ClusterIP for internal-only access or LoadBalancer for external access
