name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt


    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest journalbot\lib\python3.7\site-packages\sqlalchemy\testing

    - name: Run UnittTests
      run: |
        echo "Running Unittests..."
        pytest test_app.py

    - name: Run Flake8
      run: |
        echo "Running Flake8..."
        flake8 .

    - name: Verify Test Results
      run: |
        echo "Verifying test results..."
        # Optionally, add verification steps, for example:
        # curl -f http://localhost:8000/health || exit 1

    - name: Build Docker image
      run: |
        docker build -t journalbot .
        docker tag journalbot myrepo/my-app:latest
        docker push journalbot/my-app:latest
        
